# Site settings
title: Madalin dot me
email: hi@madalin.me
description: > # this means to ignore newlines until "baseurl:"
  Ramblings by Madalin, a passionate Web Developer, possibly living on Mars.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.madalin.me" # the base hostname & protocol for your site
company: MultiSafepay
permalink: ordinal
show_excerpts: true

# socials
twitter_username: 16nsk
github_username:  madalinignisca
linkedin_username: ibuildwebapps

# Build settings
markdown: kramdown
kramdown:
  input: GFM

theme: minima

minima:
  date_format: "%b %-d, %Y"
  social_links:
    twitter: 16nsk
    github: madalinignisca
    stackoverflow: 3303165
    linkedin: ibuildwebapps
    youtube_channel: UC7HgClRI_kS3VtUTEIrk7HQ
    youtube_channel_name: Learn with me!
    devto: madalinignisca

google_analytics: G-J3FTR7JVYW

plugins:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-spaceship

jekyll-spaceship:
  media-processor:
    default:
      id: 'media-{id}'
      class: 'media'
      width: '100%'
      height: 'auto'
      frameborder: 0
      style: 'aspect-ratio: 16 / 9;'
      allow: 'encrypted-media; picture-in-picture'